#!/usr/bin/env bash

# 
# this just runs tests/check-eval.nix
# 
result="$(
    echo 'import ./nodes/1_lib/source/tests/check-eval.nix' | nix repl 2>&1 | grep -v 'Inappropriate ioctl for device'
)"
expected='Welcome to Nix 2.18.1. Type :? for help.

[36;1mnull[0m'

if [ "$(echo "$result")" = "$expected" ]
then
    echo test passed
fi