[packageInfo]
name = "bootstrap-tools"

[osSpecific.darwin-x86-64.stdFetchurls.bootstrapTools]
url = "http://tarballs.nixos.org/stdenv/x86_64-apple-darwin/d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f/bootstrap-tools.tar.xz"
hash = "sha256-3OBigzlbu/Z6g8r7hsOWg95HTv7IJw9Nvbamwvw+88w="

[osSpecific.darwin-x86-64.stdFetchurls.unpack]
url = "http://tarballs.nixos.org/stdenv/x86_64-apple-darwin/d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f/unpack.nar.xz"
hash = "sha256-93GK8LjjgUBknxsylfGVr0DG4AbWVIQEIWrwxhDW07k="
name = "unpack"

[osSpecific.darwin-x86-64.stdMetadata]
"nixpkgsRevision" = "d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f"
"hydraBuild" = "https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-apple-darwin.build/latest"
"resolvedHydraBuild" = "https://hydra.nixos.org/build/255281731"
"instantiatedDerivation" = "/nix/store/44wnr0ikrbcxkakfqhhm2cz6gsh6wjni-stdenv-bootstrap-tools.drv"
"outputDirectory" = "/nix/store/lsl9rl3zj9nr318w471vvmlvxzj21b2k-stdenv-bootstrap-tools"
"buildTime" = "Wed, 03 Apr 2024 07:56:15 +0000"

[osSpecific.darwin-aarch-64.stdFetchurls.bootstrapTools]
url = "http://tarballs.nixos.org/stdenv/aarch64-apple-darwin/d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f/bootstrap-tools.tar.xz"
hash = "sha256-a37OgMdTHjFyKs4UTxoD7zx6Te3A7zsSjhbFHzbNxQ8="

[osSpecific.darwin-aarch-64.stdFetchurls.unpack]
url = "http://tarballs.nixos.org/stdenv/aarch64-apple-darwin/d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f/unpack.nar.xz"
hash = "sha256-XCVy6TMDJ1DKFnhIT1NHzdQUjY/TPKLV67Zi/ANIpms="
name = "unpack"

[osSpecific.darwin-aarch-64.stdMetadata]
"nixpkgsRevision" = "d03a4482228d4d6dbd2d4b425b6dfcd49ebe765f"
"hydraBuild" = "https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.aarch64-apple-darwin.build/latest"
"resolvedHydraBuild" = "https://hydra.nixos.org/build/255282138"
"instantiatedDerivation" = "/nix/store/cahnprnkg9z2aij3hj4rkbkc4l8190mf-stdenv-bootstrap-tools.drv"
"outputDirectory" = "/nix/store/zxxcz7sza5ypy061rsg7cmr7h0a96hbb-stdenv-bootstrap-tools"
"buildTime" = "Wed, 03 Apr 2024 07:59:44 +0000"
